---
#################################################
#                                               #
# Styles for markdown cards on mobile devices   #
#                                               #
#################################################

style:
  .: |
    ha-card {
      --ha-card-background: transparent;
      --ha-card-border-color: transparent;
      --ha-card-border-width: 0;
    }
    ha-markdown {
      margin-top: 16px;
      padding: 0 !important;
    }
    @media (max-width: 767px) {
      ha-card {
        display: none;
      }
    }
  ha-markdown:
    $: |
      h1 {
        font-size: 4rem;
        font-weight: bold;
        margin-bottom: 1rem;
      }
      p {
        font-size: 1.5rem;
        line-height: 1.75rem;
      }
      hr {
        border: 0 none;
        border-top: 1px solid rgba(255, 255, 255, 0.3);
        margin: 2rem 0 0 0;
        padding: 1rem 0 0 0;
      }
