---
#################################################
#                                               #
# Wallpanel                                     #
#                                               #
# https://github.com/j-a-n/lovelace-wallpanel/  #
#                                               #
#################################################

enabled: true
debug: false

hide_toolbar: false
hide_sidebar: false
fullscreen: false
card_interaction: false

image_url: https://source.unsplash.com/random/${width}x${height}?nature,${entity:sensor.openweathermap_condition}&sig=${timestamp}
image_fit: cover
image_list_update_interval: 3600
image_order: sorted
image_excludes: []

show_image_info: false
show_progress_bar: false

screensaver_entity: input_boolean.screensaver

idle_time: 90

cards:
  - type: weather-forecast
    entity: weather.openweathermap
    show_forecast: true

style:
  wallpanel-screensaver-info-box:
    background-color: rgba(0, 0, 0, 0.6)
    zoom: 0.8

  wallpanel-screensaver-info-box-content:
    "--ha-card-background": none
    "--ha-card-box-shadow": none
    "--ha-card-border-width": 0
    "--primary-background-color": rgb(0, 0, 0)
    "--secondary-background-color": rgb(44, 44, 46)
    "--primary-text-color": rgb(242, 242, 247)
    "--secondary-text-color": rgb(174, 174, 178)

  wallpanel-screensaver-image-info:
    display: none