---
#################################################
#                                               #
# Lovelace configuration                        #
#                                               #
#################################################

# Load Dashboard from lovelace/index.yaml file
!include lovelace/index.yaml